// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function ClassifyImage(arg1:string):Promise<string>;

export function DownloadImage(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ProcessImage(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function SearchImages(arg1:string,arg2:number,arg3:number):Promise<Array<services.ImageResult>>;

export function UpscaleImage(arg1:string,arg2:string,arg3:number):Promise<string>;
