// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadImage(arg1) {
  return window['go']['main']['App']['DownloadImage'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ProcessImage(arg1, arg2) {
  return window['go']['main']['App']['ProcessImage'](arg1, arg2);
}

export function SearchImages(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchImages'](arg1, arg2, arg3);
}

export function UpscaleImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpscaleImage'](arg1, arg2, arg3);
}
