// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadImage(arg1) {
  return window['go']['main']['App']['DownloadImage'](arg1);
}

export function GetDefaultSavePath() {
  return window['go']['main']['App']['GetDefaultSavePath']();
}

export function GetProcessingStatus() {
  return window['go']['main']['App']['GetProcessingStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ProcessBatch(arg1, arg2) {
  return window['go']['main']['App']['ProcessBatch'](arg1, arg2);
}

export function ProcessImage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ProcessImage'](arg1, arg2, arg3, arg4, arg5);
}

export function SearchImages(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchImages'](arg1, arg2, arg3);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function UpscaleImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpscaleImage'](arg1, arg2, arg3);
}
