// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {services} from '../models';

export function DownloadImage(arg1:string):Promise<string>;

export function GetDefaultSavePath():Promise<string>;

export function GetProcessingStatus():Promise<main.ProcessingStatus>;

export function Greet(arg1:string):Promise<string>;

export function ProcessBatch(arg1:Array<main.BatchItem>,arg2:string):Promise<void>;

export function ProcessImage(arg1:string,arg2:number,arg3:number,arg4:string,arg5:string):Promise<string>;

export function SearchImages(arg1:string,arg2:number,arg3:number):Promise<Array<services.ImageResult>>;

export function SelectDirectory():Promise<string>;

export function UpscaleImage(arg1:string,arg2:string,arg3:number):Promise<string>;
